
services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4000:3000"
    networks:
      - app


  backend:
    build:
      context: ./Node
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./Node:/usr/src/app
    depends_on:
      - mongodb
    networks:
      - app

  mongodb:
    image: mongo:latest
    container_name: mongodb-fullstack
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: assignment2db
    volumes:
      - mongo_data:/data/db
    networks:
      - app

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - app


volumes:
  mongo_data:

networks:
  app:
    driver: bridge